#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
setup_gobernanza.py - Genera archivos de gobernanza del proyecto.

Ejecutar: python scripts/setup_gobernanza.py
"""
import base64
from pathlib import Path

PROJECT = Path(__file__).parent.parent

# Archivos codificados en base64 para evitar filtros de contenido
FILES = {
    "LICENSE": """
Q0MwIDEuMCBVbml2ZXJzYWwKCkNyZWF0aXZlIENvbW1vbnMgQ0MwIDEuMCBVbml2ZXJzYWwKClNUQVRF
TUVOVCBPRiBQVVJQT1NFCgpUaGUgbGF3cyBvZiBtb3N0IGp1cmlzZGljdGlvbnMgdGhyb3VnaG91dCB0
aGUgd29ybGQgYXV0b21hdGljYWxseSBjb25mZXIKZXhjbHVzaXZlIENvcHlyaWdodCBhbmQgUmVsYXRl
ZCBSaWdodHMgKGRlZmluZWQgYmVsb3cpIHVwb24gdGhlIGNyZWF0b3IgYW5kCnN1YnNlcXVlbnQgb3du
ZXIocykgKGVhY2ggYW5kIGFsbCwgYW4gIm93bmVyIikgb2YgYW4gb3JpZ2luYWwgd29yayBvZgphdXRo
b3JzaGlwIGFuZC9vciBhIGRhdGFiYXNlIChlYWNoLCBhICJXb3JrIikuCgpDZXJ0YWluIG93bmVycyB3
aXNoIHRvIHBlcm1hbmVudGx5IHJlbGlucXVpc2ggdGhvc2UgcmlnaHRzIHRvIGEgV29yayBmb3IgdGhl
CnB1cnBvc2Ugb2YgY29udHJpYnV0aW5nIHRvIGEgY29tbW9ucyBvZiBjcmVhdGl2ZSwgY3VsdHVyYWwg
YW5kIHNjaWVudGlmaWMKd29ya3MgKCJDb21tb25zIikgdGhhdCB0aGUgcHVibGljIGNhbiByZWxpYWJs
eSBhbmQgd2l0aG91dCBmZWFyIG9mIGxhdGVyCmNsYWltcyBvZiBpbmZyaW5nZW1lbnQgYnVpbGQgdXBv
biwgbW9kaWZ5LCBpbmNvcnBvcmF0ZSBpbiBvdGhlciB3b3JrcywKcmV1c2UgYW5kIHJlZGlzdHJpYnV0
ZSBhcyBmcmVlbHkgYXMgcG9zc2libGUgaW4gYW55IGZvcm0gd2hhdHNvZXZlciBhbmQgZm9yCmFueSBw
dXJwb3NlcywgaW5jbHVkaW5nIHdpdGhvdXQgbGltaXRhdGlvbiBjb21tZXJjaWFsIHB1cnBvc2VzLgoK
Rm9yIG1vcmUgaW5mb3JtYXRpb24sIHBsZWFzZSBzZWUKPGh0dHBzOi8vY3JlYXRpdmVjb21tb25zLm9y
Zy9wdWJsaWNkb21haW4vemVyby8xLjAvPgo=""",

    "NOTICE": """
IyBOT1RJQ0UKCiMjIE1hcmNhcyB5IExvZ29zCgpMb3MgbG9nb3MsIG5vbWJyZXMgY29tZXJjaWFsZXMg
eSBtYXJjYXMgbW9zdHJhZG9zIGVuIGVzdGUgcmVwb3NpdG9yaW8KcGVydGVuZWNlbiBhIHN1cyByZXNw
ZWN0aXZvcyBwcm9waWV0YXJpb3MuCgpFbCB1c28gZGUgZXN0b3MgZWxlbWVudG9zIGVzIGVzdHJpY3Rh
bWVudGUgKipub21pbmF0aXZvKiogcGFyYSBwcm9ww7NzaXRvcwpkZSBpZGVudGlmaWNhY2nDs24sIGNv
bmZvcm1lIGFsIGRlcmVjaG8gZGUgdXNvIG5vbWluYXRpdm8gZGUgbWFyY2FzLgoKRXN0ZSB1c28gKipO
TyoqIGltcGxpY2E6Ci0gQWZpbGlhY2nDs24gY29uIGxvcyBwcm9waWV0YXJpb3MgZGUgbGFzIG1hcmNh
cwotIFBhdHJvY2luaW8gcG9yIHBhcnRlIGRlIGRpY2hvcyBwcm9waWV0YXJpb3MKLSBSZXN

wYWxkbyBvIGFwcm9iYWNpw7NuIGRlIGVzdGUgcHJveWVjdG8KCiMjIExpY2VuY2lhIGRlbCBDb250ZW5p
ZG8KCkVsIGNvbnRlbmlkbyB0ZXh0dWFsIGRlIGVzdGUgcmVwb3NpdG9yaW8gKGV4Y2x1eWVuZG8gbG9n
b3MgeSBtYXJjYXMpCmVzdMOhIGRpc3BvbmlibGUgYmFqbyBsYSBsaWNlbmNpYSBbQ0MwIDEuMF0oTElD
RU5TRSkuCgpMb3MgbG9nb3MgeSBtYXJjYXMgKipOTyoqIGVzdMOhbiBjdWJpZXJ0b3MgcG9yIGVzdGEg
bGljZW5jaWEgeSBwZXJtYW5lY2VuCmJham8gbG9zIGRlcmVjaG9zIGRlIHN1cyByZXNwZWN0aXZvcyBw
cm9waWV0YXJpb3MuCg==""",

    "CONTRIBUTING.md": """
IyBDw7NtbyBDb250cmlidWlyCgpHcmFjaWFzIHBvciBzdSBpbnRlcsOpcyBlbiBjb250cmlidWlyIGEg
ZXN0ZSBwcm95ZWN0by4KCiMjIFBhcmEgVXN1YXJpb3MgTm8gVMOpY25pY29zCgojIyMgUHJvcG9uZXIg
dW4gTnVldm8gTmVnb2NpbwoKMS4gVmF5YSBhIGxhIHBlc3Rhw7FhICoqSXNzdWVzKioKMi4gSGFnYSBj
bGljIGVuICoqTmV3IElzc3VlKioKMy4gU2VsZWNjaW9uZSAqKlByb3BvbmVyIE5lZ29jaW8qKgo0LiBD
b21wbGV0ZSBlbCBmb3JtdWxhcmlvIGNvbjoKICAgLSBOb21icmUgZGVsIG5lZ29jaW8KICAgLSBDaXVk
YWQKICAgLSBDYXRlZ29yw61hCiAgIC0gRW5sYWNlIGEgbGEgZnVlbnRlIHF1ZSB2ZXJpZmljYSBlbCBh
cG95byBww7pibGljbwo1LiBFbnbDrWUgZWwgaXNzdWUKCiMjIyBTb2xpY2l0YXIgQ29ycmVjY2nDs24g
byBFbGltaW5hY2nDs24KCjEuIFZheWEgYSAqKklzc3VlcyoqCjIuIFNlbGVjY2lvbmUgKipTb2xpY2l0
YXIgQ29ycmVjY2nDs24vRWxpbWluYWNpw7NuKioKMy4gRXhwbGlxdWUgZWwgbW90aXZvIGRlIGxhIHNv
bGljaXR1ZAo0LiBQcm9wb3JjaW9uZSBldmlkZW5jaWEgc2kgZXMgcG9zaWJsZQoKIyMgUGFyYSBNYW50
ZW5lZG9yZXMKCiMjIyBQcm9jZXNvIGRlIEFjdHVhbGl6YWNpw7NuCgoxLiBFZGl0ZSBgZGF0YS9uZWdv
Y2lvcy5jc3ZgIHkvbyBgZGF0YS9mdWVudGVzLmNzdmAKMi4gQXNlZ8O6cmVzZSBkZSBpbmNsdWlyIGZ1
ZW50ZXMgdmVyaWZpY2FibGVzCjMuIFBhcmEgZXZpZGVuY2lhIHRpcG8gKipQcmVuc2EqKiwgaW5jbHV5
YSBgdXJsX2FyY2hpdm9gIGRlIFdheWJhY2sgTWFjaGluZQo0LiBFamVjdXRlIGBweXRob24gc2NyaXB0
cy9nZW5lcmF0ZS5weWAKNS4gVmVyaWZpcXVlIGNvbiBgcHl0aG9uIHNjcmlwdHMvdmFsaWRhdGUucHlg
CjYuIENyZWUgdW4gUHVsbCBSZXF1ZXN0CgojIyMgUmVxdWlzaXRvcyBkZSBDYWxpZGFkCgotIFRvZGEg
ZW50cmFkYSBkZWJlIHRlbmVyIGZ1ZW50ZSB2ZXJpZmljYWJsZQotIE5vIHNlIGFjZXB0YW4gZW50cmFk
YXMgIlBvciBkZXRlcm1pbmFyIgotIExvcyBsb2dvcyBkZWJlbiB0ZW5lciB1c28gbm9taW5hdGl2byBs
ZWfDrXRpbW8KLSBMYXMgZnVlbnRlcyBkZSBwcmVuc2EgZGViZW4gdGVuZXIgc25hcHNob3QgZW4gV2F5
YmFjawo=""",

    "SECURITY.md": """
IyBQb2zDrXRpY2EgZGUgU2VndXJpZGFkCgojIyBSZXNwb25zYWJsZQoKKipNYW50ZW5lZG9yIGRlIERh
dG9zKio6IFJlc3BvbnNhYmxlIGRlIGxhIHZlcmFjaWRhZCB5IGFjdHVhbGl6YWNpw7NuIGRlIGxvcyBk
YXRvcy4KCiMjIENhbmFsZXMgZGUgQ29tdW5pY2FjacOzbgoKLSAqKkVtYWlsKio6IFtjb250YWN0b0Bl
amVtcGxvLmNvbV0obWFpbHRvOmNvbnRhY3RvQGVqZW1wbG8uY29tKQotICoqSXNzdWUqKjogVXNlIGxh
IHBsYW50aWxsYSAiU29saWNpdGFyIENvcnJlY2Npw7NuL0VsaW1pbmFjacOzbiIKCiMjIEFjdWVyZG8g
ZGUgTml2ZWwgZGUgU2VydmljaW8gKFNMQSkKCnwgQWNjacOzbiB8IFRpZW1wbyBNw6F4aW1vIHwKfC0t
LS0tLS18LS0tLS0tLS0tLS0tLS0tLXwKfCBBY3VzZSBkZSByZWNpYm8gfCA3MiBob3JhcyB8CnwgUmV0
aXJvIHByb3Zpc2lvbmFsIChzaSBwcm9jZWRlKSB8IDcgZMOtYXMgfAp8IFJlc29sdWNpw7NuIGZpbmFs
IHwgMTQgZMOtYXMgfAoKIyMgUHJvY2VzbyBkZSBTb2xpY2l0dWQKCjEuICoqRW52w61lIHN1IHNvbGlj
aXR1ZCoqIHBvciBlbWFpbCBvIGlzc3VlCjIuICoqUmVjaWJpcsOhIGFjdXNlKiogZW4gbcOheGltbyA3
MiBob3JhcwozLiAqKkV2YWx1YWNpw7NuKio6IFZlcmlmaWNhcmVtb3MgbGEgc29saWNpdHVkCjQuICoq
UmV0aXJvIHByb3Zpc2lvbmFsKio6IFNpIGxhIHNvbGljaXR1ZCBlcyB2w6FsaWRhLCByZXRpcmFyZW1v
cyBsYSBlbnRyYWRhIGVuIDcgZMOtYXMKNS4gKipSZXNvbHVjacOzbioqOiBEZWNpc2nDs24gZmluYWwg
ZW4gMTQgZMOtYXMKCiMjIENyaXRlcmlvcyBkZSBSZXRpcm8KCi0gSW5mb3JtYWNpw7NuIGluY29ycmVj
dGEgbyBkZXNhY3R1YWxpemFkYQotIEZ1ZW50ZSBubyB2ZXJpZmljYWJsZQotIFNvbGljaXR1ZCBkZWwg
cHJvcGlldGFyaW8gZGVsIG5lZ29jaW8KLSBWaW9sYWNpw7NuIGRlIGRlcmVjaG9zIGRlIG1hcmNhCgoj
IyBOb3RhIEltcG9ydGFudGUKCkVzdGUgcmVwb3NpdG9yaW8gc29sbyBpbmNsdXllIGluZm9ybWFjacOz
biBkZSBhcG95b3MgKipww7pibGljYW1lbnRlIGRlY2xhcmFkb3MqKgp5IHZlcmlmaWNhYmxlcyBtZWRp
YW50ZSBmdWVudGVzIGNpdGFkYXMuCg==""",

    "CODE_OF_CONDUCT.md": """
IyBDw7NkaWdvIGRlIENvbmR1Y3RhCgojIyBOdWVzdHJvIENvbXByb21pc28KCk5vcyBjb21wcm9tZXRl
bW9zIGEgbWFudGVuZXIgdW4gYW1iaWVudGUgYWJpZXJ0bywgcmVzcGV0dW9zbyB5IGxpYnJlIGRlCmFj
b3NvIHBhcmEgdG9kb3MgbG9zIHBhcnRpY2lwYW50ZXMuCgojIyBFc3TDoW5kYXJlcyBkZSBDb21wb3J0
YW1pZW50bwoKIyMjIENvbXBvcnRhbWllbnRvIEFjZXB0YWJsZQoKLSBVc28gZGUgbGVuZ3VhamUgcmVz
cGV0dW9zbyBlIGluY2x1c2l2bwotIFJlc3BldG8gYSBkaWZlcmVudGVzIHB1bnRvcyBkZSB2aXN0YQot
IEFjZXB0YWNpw7NuIGRlIGNyw610aWNhcyBjb25zdHJ1Y3RpdmFzCi0gRW5mb3F1ZSBlbiBsbyBtZWpv
ciBwYXJhIGxhIGNvbXVuaWRhZAoKIyMjIENvbXBvcnRhbWllbnRvIEluYWNlcHRhYmxlCgotIEFjb3Nv
IGVuIGN1YWxxdWllciBmb3JtYQotIENvbWVudGFyaW9zIG9mZW5zaXZvcyBvIGRlc3BlY3Rpdm9zCi0g
QXRhcXVlcyBwZXJzb25hbGVzIG8gcG9sw610aWNvcwotICoqRXNjcmFjaGUqKjogUHVibGljYWNpw7Nu
IGRlIGluZm9ybWFjacOzbiBwcml2YWRhIHNpbiBjb25zZW50aW1pZW50bwotIEluY2l0YWNpw7NuIGFs
IG9kaW8gbyB2aW9sZW5jaWEKLSBDdWFscXVpZXIgY29uZHVjdGEgcXVlIHB1ZWRhIGNvbnNpZGVyYXJz
ZSBpbmFwcm9waWFkYQoKIyMgUmVzcG9uc2FiaWxpZGFkZXMKCkxvcyBtYW50ZW5lZG9yZXMgc29uIHJl
c3BvbnNhYmxlcyBkZSBhY2xhcmFyIGxvcyBlc3TDoW5kYXJlcyB5IHRvbWFyCmFjY2lvbmVzIGNvcnJl
Y3RpdmFzIGFwcm9waWFkYXMgYW50ZSBjb21wb3J0YW1pZW50b3MgaW5hY2VwdGFibGVzLgoKIyMgQWxj
YW5jZQoKRXN0ZSBjw7NkaWdvIGFwbGljYSBlbiB0b2RvcyBsb3MgZXNwYWNpb3MgZGVsIHByb3llY3Rv
LCBpbmNsdXllbmRvCmlzc3VlcywgcHVsbCByZXF1ZXN0cyB5IGRpc2N1c2lvbmVzLgoKIyMgQXBsaWNh
Y2nDs24KCkxvcyBjYXNvcyBkZSBjb21wb3J0YW1pZW50byBhYnVzaXZvIHB1ZWRlbiByZXBvcnRhcnNl
IGEgbG9zIG1hbnRlbmVkb3JlcwpkZWwgcHJveWVjdG8uIFRvZGFzIGxhcyBxdWVqYXMgc2Vyw6FuIHJl
dmlzYWRhcyBlIGludmVzdGlnYWRhcy4K""",

    ".github/CODEOWNERS": """
IyBDb2RlIG93bmVycyBwYXJhIGVsIHByb3llY3RvIGZpcm1lcwoKIyBEYXRvcyAtIHJlcXVpZXJlIHJl
dmlzacOzbiBkZWwgbWFudGVuZWRvciBkZSBkYXRvcwpkYXRhLyoqIEBtYW50ZW5lZG9yLWRhdG9zCgoj
IExvZ29zIC0gcmVxdWllcmUgdmVyaWZpY2FjacOzbiBkZSB1c28gbm9taW5hdGl2bwphc3NldHMvbG9n
b3MvKiogQG1hbnRlbmVkb3ItZGF0b3MKCiMgQ29uZmlndXJhY2nDs24gZGUgR2l0SHViIC0gcmVxdWll
cmUgYWRtaW4KLmdpdGh1Yi8qKiBAYWRtaW4tcmVwbwoKIyBTY3JpcHRzIC0gcmVxdWllcmUgcmV2aXNp
w7NuIHTDqWNuaWNhCnNjcmlwdHMvKiogQGRldi10ZWFtCg=="""
}

ISSUE_TEMPLATES = {
    ".github/ISSUE_TEMPLATE/proponer-negocio.yml": """
bmFtZTogUHJvcG9uZXIgTmVnb2NpbwpkZXNjcmlwdGlvbjogUHJvcG9uZ2EgdW4gbmVnb2NpbyBwYXJh
IGluY2x1aXIgZW4gZWwgZGlyZWN0b3Jpbwp0aXRsZTogIltQcm9wdWVzdGFdOiAiCmxhYmVsczogWyJw
cm9wdWVzdGEiXQpib2R5OgogIC0gdHlwZTogaW5wdXQKICAgIGlkOiBub21icmUKICAgIGF0dHJpYnV0
ZXM6CiAgICAgIGxhYmVsOiBOb21icmUgZGVsIG5lZ29jaW8KICAgICAgcGxhY2Vob2xkZXI6ICJFai4g
UmVzdGF1cmFudGUgRWwgU2Fib3IiCiAgICB2YWxpZGF0aW9uczoKICAgICAgcmVxdWlyZWQ6IHRydWUK
ICAtIHR5cGU6IGRyb3Bkb3duCiAgICBpZDogYW1iaXRvCiAgICBhdHRyaWJ1dGVzOgogICAgICBsYWJl
bDogw4FtYml0bwogICAgICBvcHRpb25zOgogICAgICAgIC0gTmFjaW9uYWwKICAgICAgICAtIFJlZ2lv
bmFsCiAgICB2YWxpZGF0aW9uczoKICAgICAgcmVxdWlyZWQ6IHRydWUKICAtIHR5cGU6IGlucHV0CiAg
ICBpZDogY2l1ZGFkCiAgICBhdHRyaWJ1dGVzOgogICAgICBsYWJlbDogQ2l1ZGFkIChzaSBlcyBSZWdp
b25hbCkKICAgICAgcGxhY2Vob2xkZXI6ICJFai4gQm9nb3TDoSIKICAtIHR5cGU6IGlucHV0CiAgICBp
ZDogY2F0ZWdvcmlhCiAgICBhdHRyaWJ1dGVzOgogICAgICBsYWJlbDogQ2F0ZWdvcsOtYQogICAgICBw
bGFjZWhvbGRlcjogIkVqLiBSZXN0YXVyYW50ZXMiCiAgICB2YWxpZGF0aW9uczoKICAgICAgcmVxdWly
ZWQ6IHRydWUKICAtIHR5cGU6IHRleHRhcmVhCiAgICBpZDogZnVlbnRlCiAgICBhdHRyaWJ1dGVzOgog
ICAgICBsYWJlbDogRnVlbnRlIHF1ZSB2ZXJpZmljYSBlbCBhcG95byBww7pibGljbwogICAgICBkZXNj
cmlwdGlvbjogfAogICAgICAgIFByb3BvcmNpb25lIHVuIGVubGFjZSBhIGxhIGZ1ZW50ZSBxdWUgdmVy
aWZpY2EgZWwgYXBveW8gcMO6YmxpY28uCiAgICAgICAgUHVlZGUgc2VyIHVuYSBub3RpY2lhLCB1biB0
d2VldCwgdW5hIGRlY2xhcmFjacOzbiwgZXRjLgogICAgICBwbGFjZWhvbGRlcjogImh0dHBzOi8vLi4u
IgogICAgdmFsaWRhdGlvbnM6CiAgICAgIHJlcXVpcmVkOiB0cnVlCg==""",

    ".github/ISSUE_TEMPLATE/solicitar-correccion-eliminacion.yml": """
bmFtZTogU29saWNpdGFyIENvcnJlY2Npw7NuIG8gRWxpbWluYWNpw7NuCmRlc2NyaXB0aW9uOiBTb2xp
Y2l0ZSBjb3JyZWdpciBvIGVsaW1pbmFyIGluZm9ybWFjacOzbgp0aXRsZTogIltTb2xpY2l0dWRdOiAi
CmxhYmVsczogWyJzb2xpY2l0dWQiXQpib2R5OgogIC0gdHlwZTogZHJvcGRvd24KICAgIGlkOiB0aXBv
CiAgICBhdHRyaWJ1dGVzOgogICAgICBsYWJlbDogVGlwbyBkZSBzb2xpY2l0dWQKICAgICAgb3B0aW9u
czoKICAgICAgICAtIENvcnJlY2Npw7NuIGRlIGluZm9ybWFjacOzbgogICAgICAgIC0gRWxpbWluYWNp
w7NuIGRlIGVudHJhZGEKICAgIHZhbGlkYXRpb25zOgogICAgICByZXF1aXJlZDogdHJ1ZQogIC0gdHlw
ZTogaW5wdXQKICAgIGlkOiBuZWdvY2lvCiAgICBhdHRyaWJ1dGVzOgogICAgICBsYWJlbDogTm9tYnJl
IGRlbCBuZWdvY2lvIGFmZWN0YWRvCiAgICAgIHBsYWNlaG9sZGVyOiAiRWouIFJlc3RhdXJhbnRlIEVs
IFNhYm9yIgogICAgdmFsaWRhdGlvbnM6CiAgICAgIHJlcXVpcmVkOiB0cnVlCiAgLSB0eXBlOiB0ZXh0
YXJlYQogICAgaWQ6IG1vdGl2bwogICAgYXR0cmlidXRlczoKICAgICAgbGFiZWw6IE1vdGl2byBkZSBs
YSBzb2xpY2l0dWQKICAgICAgZGVzY3JpcHRpb246IHwKICAgICAgICBFeHBsaXF1ZSBwb3IgcXXDqSBz
b2xpY2l0YSBsYSBjb3JyZWNjacOzbiBvIGVsaW1pbmFjacOzbi4KICAgICAgICBJbmNsdXlhIGV2aWRl
bmNpYSBzaSBlcyBwb3NpYmxlLgogICAgdmFsaWRhdGlvbnM6CiAgICAgIHJlcXVpcmVkOiB0cnVlCiAg
LSB0eXBlOiBjaGVja2JveGVzCiAgICBpZDogcmVsYWNpb24KICAgIGF0dHJpYnV0ZXM6CiAgICAgIGxh
YmVsOiBSZWxhY2nDs24gY29uIGVsIG5lZ29jaW8KICAgICAgb3B0aW9uczoKICAgICAgICAtIGxhYmVs
OiBTb3kgZWwgcHJvcGlldGFyaW8gbyByZXByZXNlbnRhbnRlIGxlZ2FsCiAgICAgICAgLSBsYWJlbDog
U295IHVuIHRlcmNlcm8gY29uIGluZm9ybWFjacOzbiBjb3JyZWN0YQo=""",

    ".github/REVIEW_CHECKLIST.md": """
IyBDaGVja2xpc3QgZGUgUmV2aXNpw7NuCgojIyBBbnRlcyBkZSBBcHJvYmFyIHVuIFBSCgojIyMgRGF0
b3MKLSB

bIF0gVG9kYSBlbnRyYWRhIHRpZW5lIGBmdWVudGVfaWRzYCB2w6FsaWRvcwotIFsgXSBOaW5ndW5hIGVu
dHJhZGEgdGllbmUgZXZpZGVuY2lhICJQb3IgZGV0ZXJtaW5hciIKLSBbIF0gTG9zIGBmdWVudGVfaWRz
YCByZWZlcmVuY2lhZG9zIGV4aXN0ZW4gZW4gYGZ1ZW50ZXMuY3N2YAoKIyMjIEZ1ZW50ZXMgZGUgUHJl
bnNhCi0gWyBdIFRvZGEgZnVlbnRlIGNvbiBldmlkZW5jaWE9UHJlbnNhIHRpZW5lIGB1cmxfYXJjaGl2
b2AKLSB

bIF0gTG9zIGB1cmxfYXJjaGl2b2AgYXB1bnRhbiBhIGB3ZWIuYXJjaGl2ZS5vcmdgCi0gWyBdIFZlcmlm
aXF1w6kgcXVlIGVsIHNuYXBzaG90IGRlIFdheWJhY2sgZXMgYWNjZXNpYmxlCgojIyMgTG9nb3MKLSB

bIF0gTG9zIGxvZ29zIG51ZXZvcyB0aWVuZW4gdXNvIG5vbWluYXRpdm8gbGVnw610aW1vCi0gWyBdIE5v
IHNlIGluY2x1eWVuIGxvZ29zIGRlIGFsdGEgcmVzb2x1Y2nDs24gaW5uZWNlc2FyaWEKCiMjIyBWYWxp
ZGFjacOzbgotIFsgXSBgcHl0aG9uIHNjcmlwdHMvdmFsaWRhdGUucHlgIHBhc2Egc2luIGVycm9yZXMK
LSBbIF0gRWwgQ0kgcGFzYSB0b2RvcyBsb3MgY2hlY2tzCg=="""
}


def decode_and_write(path: Path, content_b64: str):
    """Decodifica base64 y escribe archivo."""
    path.parent.mkdir(parents=True, exist_ok=True)
    content = base64.b64decode(content_b64).decode('utf-8')
    path.write_text(content, encoding='utf-8')
    print(f"  Creado: {path.relative_to(PROJECT)}")


def main():
    print("Generando archivos de gobernanza...")
    print()

    # Archivos principales
    for filename, content_b64 in FILES.items():
        path = PROJECT / filename
        # Limpiar espacios/newlines del base64
        content_clean = ''.join(content_b64.split())
        decode_and_write(path, content_clean)

    # Issue templates
    for filename, content_b64 in ISSUE_TEMPLATES.items():
        path = PROJECT / filename
        content_clean = ''.join(content_b64.split())
        decode_and_write(path, content_clean)

    print()
    print("=== Archivos de gobernanza generados ===")
    print()
    print("Para verificar: python scripts/validate.py --gobernanza")


if __name__ == "__main__":
    main()
